### ISSUE TITLE
The screen goes blank when deleting or creating files.

### ISSUE THREAD

**Issue by alanbosco** [imshubhamsingh/file-system-react#2]
Steps to reproduce: delete or create a file.
development environment: firefox 67.0b14, windows 10.

Log: 
The above error occurred in the <HelmetWrapper> component:
    in HelmetWrapper (created by SEO)
    in SEO (created by Grid)
    in div (created by Context.Consumer)
    in StyledComponent (created by Grid__Container)
    in Grid__Container (created by Grid)
    in Grid (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by ViewFiles)
    in div (created by Context.Consumer)
    in StyledComponent (created by ViewFiles__Container)
    in ViewFiles__Container (created by ViewFiles)
    in ViewFiles (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in Provider (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.development.js:17117:12
too much recursion

**Comment by imshubhamsingh** [comment]
@alanbosco Is this happing on local env? Can you also please test this on other browser?
