### ISSUE TITLE
How to host on Netlify

### ISSUE THREAD

**Issue by Kikobeats** [imshubhamsingh/file-system-react#3]
Hello,

Loving this project; It's a perfect complement for adding a UI for anything hosted statically.

I saw you are hosting your demo at Netlify; Just I want to know how to do the same since it's not clear 🤔

I want to suggest that, ideally, could be easier to load it from a CDN; Then, just you need to declare an `index.html` entry file calling the library.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body></body>
/* loading react dependencies */
<script src="https://cdn.jsdelivr.net/npm/react@16/umd/react.production.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.production.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/styled-components@4/dist/styled-components.min.js"></script>

/* loading the lib */
<script src="https://cdn.jsdelivr.net/npm/imshubhamsingh/file-system-react/dist/index.min.js"></script>

/* initialize the lib */
<script>
fileSystemReact({ folder : 'dist' })
</script
</html>
```

Thoughts?

**Comment by imshubhamsingh** [comment]
@Kikobeats I like your method. I can be used for production purpose. Currently I'm using `parcel-bundler`, which is doing all the heavy lifting, and hosting just the `dist` folder on netlify.

**Comment by Kikobeats** [comment]
hey @imshubhamsingh looks like the website is showing nothing https://file-system-react.netlify.com/

BTW, are you closing the issue causes is it a simple way to use the library or not yet? 🙂

**Comment by imshubhamsingh** [comment]
I'll look into this as to why its failing. At the moment, I'm quite busy these days. If you want to pick it up as a task. I'll be happy to support it.
